[package]
name = "land_libs"
version = "0.1.0"
authors = ["Jeb"]

[dependencies]
krpc_mars = { git = "https://github.com/Cahu/krpc-mars" }
failure = "0.1.8"

[build-dependencies]
krpc_mars_terraformer = { git = "https://github.com/Cahu/krpc-mars-terraformer" }
glob = "*"

protoc-rust = "2.0"
